<?php

$viewModel      = $block->getPost();
$postCollection = $viewModel->getPostsCollection();

/** @var Modules\Blog\Model\Post $post */
foreach ($postCollection as $post): ?>
    <a href="<?= $viewModel->generateUrl($post->getSlug()); ?>">
        <div>
            <h1><?= $post->getTitle(); ?></h1>
            <img src="<?= $post->getImagePath(); ?>"/>
        </div>
    </a>
<?php endforeach; ?>